import {
  Brain,
  ShieldAlert,
  Target,
  Microscope,
} from "lucide-react";

import RiskBadge from "../RiskBadge";

const PredictionSummary = () => {
  return (
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">

      {/* Section Header */}
      <div className="flex items-center gap-3">

        <div className="rounded-2xl bg-sky-100 p-3">
          <Brain className="h-6 w-6 text-sky-600" />
        </div>

        <div>
          <h2 className="text-xl font-bold text-slate-800">
            AI Prediction Summary
          </h2>

          <p className="text-sm text-slate-500">
            Primary diagnosis generated by the AI model.
          </p>
        </div>

      </div>

      {/* Main Prediction */}
      <div className="mt-8 rounded-2xl border border-sky-100 bg-sky-50 p-6">

        <div className="flex flex-wrap items-center justify-between gap-4">

          <div>
            <p className="text-sm text-slate-500">
              Predicted Disease
            </p>

            <h3 className="mt-2 text-3xl font-bold text-slate-800">
              Melanocytic Nevus
            </h3>
          </div>

          <RiskBadge risk="Low" />

        </div>

      </div>

      {/* Metrics */}
      <div className="mt-6 grid gap-5 md:grid-cols-3">

        <MetricCard
          icon={Target}
          label="Confidence"
          value="98.4%"
          color="text-sky-600"
        />

        <MetricCard
          icon={ShieldAlert}
          label="Risk Level"
          value="Low"
          color="text-green-600"
        />

        <MetricCard
          icon={Microscope}
          label="AI Model"
          value="EfficientNetV2"
          color="text-violet-600"
        />

      </div>

    </section>
  );
};

const MetricCard = ({
  icon: Icon,
  label,
  value,
  color,
}) => {
  return (
    <div className="rounded-2xl border border-slate-100 bg-slate-50 p-5">

      <div className="flex items-center gap-3">

        <div className="rounded-xl bg-white p-3 shadow-sm">
          <Icon className={`h-5 w-5 ${color}`} />
        </div>

        <div>
          <p className="text-sm text-slate-500">
            {label}
          </p>

          <h4 className={`mt-1 text-lg font-bold ${color}`}>
            {value}
          </h4>
        </div>

      </div>

    </div>
  );
};

export default PredictionSummary;